name: Check-out

on:
  workflow_dispatch:

jobs:
  RunCode:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python src/main.py \
            --box-name=${{ vars.BOX_NAME }} --box-id=${{ vars.BOX_ID }} \
            --days-in-advance=20 \
            --days-off-file "days_off.txt" \
            --booking-goals-yaml-file "booking_goals.yaml" \
            --password "${{ secrets.JOSE_PASSWORD }}" \
            --email ${{ secrets.JOSE_EMAIL }}
